### ISSUE TITLE
Error al listar rutas

### ISSUE THREAD

**Issue by EmmanuelAB** [xsaco07/CR-Route#25]
En cada card se pone "Ruta #1" pero 1 es el id en la base no el número de ruta (ruta nacional 200 por ejemplo) como debería ser

**Comment by EmmanuelAB** [comment]
![image](https://user-images.githubusercontent.com/26278460/68638489-589e6500-04c7-11ea-9a4f-3636e036eb8b.png)

**Comment by fernando-rojas12** [comment]
Listo en el #42 se arregla
